In [1]:
import os

In [2]:
dataset_path = 'C:/pythonn/plant_desease/augmented_new_two'

In [3]:
num_healthy_images = len(os.listdir(os.path.join(dataset_path, 'healthy')))
num_rust_images = len(os.listdir(os.path.join(dataset_path, 'rust')))

In [4]:
print("Number of healthy images:", num_healthy_images)
print("Number of rust images:", num_rust_images)

Number of healthy images: 2000
Number of rust images: 2000


In [5]:
def load_and_preprocess_images(image_folder):
    image_files = os.listdir(image_folder)
    images = []
    for image_file in image_files:
        image_path = os.path.join(image_folder, image_file)
        image = cv2.imread(image_path)
        if image is not None:
            image = cv2.resize(image, (256, 256))
            images.append(image)
    return images

In [6]:
import cv2

In [7]:
healthy_files = load_and_preprocess_images(os.path.join(dataset_path, 'healthy'))
rust_files = load_and_preprocess_images(os.path.join(dataset_path, 'rust'))

In [8]:
healthy_files

[array([[[ 12,  30,  30],
         [  8,  27,  30],
         [  9,  28,  35],
         ...,
         [ 11,  81,  54],
         [ 10,  77,  50],
         [  8,  75,  49]],
 
        [[177, 195, 229],
         [171, 196, 232],
         [166, 197, 239],
         ...,
         [ 23,  93,  70],
         [ 24,  96,  73],
         [ 30, 102,  79]],
 
        [[148, 191, 230],
         [146, 188, 230],
         [146, 187, 232],
         ...,
         [ 40,  85,  67],
         [ 29,  85,  70],
         [ 33,  88,  74]],
 
        ...,
 
        [[ 19,  31,  35],
         [ 23,  35,  39],
         [ 14,  26,  30],
         ...,
         [ 47, 161, 137],
         [ 54, 172, 147],
         [ 51, 170, 145]],
 
        [[ 23,  35,  39],
         [ 14,  26,  30],
         [ 12,  24,  28],
         ...,
         [ 43, 157, 134],
         [ 51, 166, 139],
         [ 51, 166, 139]],
 
        [[ 18,  30,  34],
         [ 11,  23,  27],
         [ 18,  30,  34],
         ...,
         [ 56, 173, 148],
  

In [9]:
rust_files

[array([[[ 30, 109,  66],
         [ 37, 115,  74],
         [ 47, 124,  86],
         ...,
         [ 58,  83, 109],
         [ 78, 105, 126],
         [ 82,  99, 120]],
 
        [[ 32, 110,  72],
         [ 36, 113,  78],
         [ 42, 118,  87],
         ...,
         [ 65,  96, 112],
         [ 60,  87, 107],
         [ 77,  92, 118]],
 
        [[ 34, 113,  73],
         [ 37, 115,  77],
         [ 42, 118,  85],
         ...,
         [ 71, 107, 112],
         [ 56,  87, 103],
         [ 73,  90, 117]],
 
        ...,
 
        [[ 56, 145,  98],
         [ 68, 151, 106],
         [ 62, 152, 106],
         ...,
         [ 28, 123, 102],
         [ 20, 113,  86],
         [ 26, 109,  77]],
 
        [[ 52, 146, 101],
         [ 68, 150, 107],
         [ 72, 153, 111],
         ...,
         [ 22, 117,  97],
         [ 17, 111,  83],
         [ 22, 106,  72]],
 
        [[ 60, 160, 118],
         [ 63, 146, 107],
         [ 55, 130,  92],
         ...,
         [ 28, 122, 105],
  

In [10]:
import numpy as np

In [11]:
healthy_files = np.array(healthy_files).reshape(-1, 256, 256, 3)
rust_files = np.array(rust_files).reshape(-1, 256, 256, 3)

In [12]:
healthy_files

array([[[[ 12,  30,  30],
         [  8,  27,  30],
         [  9,  28,  35],
         ...,
         [ 11,  81,  54],
         [ 10,  77,  50],
         [  8,  75,  49]],

        [[177, 195, 229],
         [171, 196, 232],
         [166, 197, 239],
         ...,
         [ 23,  93,  70],
         [ 24,  96,  73],
         [ 30, 102,  79]],

        [[148, 191, 230],
         [146, 188, 230],
         [146, 187, 232],
         ...,
         [ 40,  85,  67],
         [ 29,  85,  70],
         [ 33,  88,  74]],

        ...,

        [[ 19,  31,  35],
         [ 23,  35,  39],
         [ 14,  26,  30],
         ...,
         [ 47, 161, 137],
         [ 54, 172, 147],
         [ 51, 170, 145]],

        [[ 23,  35,  39],
         [ 14,  26,  30],
         [ 12,  24,  28],
         ...,
         [ 43, 157, 134],
         [ 51, 166, 139],
         [ 51, 166, 139]],

        [[ 18,  30,  34],
         [ 11,  23,  27],
         [ 18,  30,  34],
         ...,
         [ 56, 173, 148],
        

In [13]:
rust_files

array([[[[ 30, 109,  66],
         [ 37, 115,  74],
         [ 47, 124,  86],
         ...,
         [ 58,  83, 109],
         [ 78, 105, 126],
         [ 82,  99, 120]],

        [[ 32, 110,  72],
         [ 36, 113,  78],
         [ 42, 118,  87],
         ...,
         [ 65,  96, 112],
         [ 60,  87, 107],
         [ 77,  92, 118]],

        [[ 34, 113,  73],
         [ 37, 115,  77],
         [ 42, 118,  85],
         ...,
         [ 71, 107, 112],
         [ 56,  87, 103],
         [ 73,  90, 117]],

        ...,

        [[ 56, 145,  98],
         [ 68, 151, 106],
         [ 62, 152, 106],
         ...,
         [ 28, 123, 102],
         [ 20, 113,  86],
         [ 26, 109,  77]],

        [[ 52, 146, 101],
         [ 68, 150, 107],
         [ 72, 153, 111],
         ...,
         [ 22, 117,  97],
         [ 17, 111,  83],
         [ 22, 106,  72]],

        [[ 60, 160, 118],
         [ 63, 146, 107],
         [ 55, 130,  92],
         ...,
         [ 28, 122, 105],
        

In [14]:
all_files = np.concatenate((healthy_files, rust_files), axis=0)

In [15]:
all_files

array([[[[ 12,  30,  30],
         [  8,  27,  30],
         [  9,  28,  35],
         ...,
         [ 11,  81,  54],
         [ 10,  77,  50],
         [  8,  75,  49]],

        [[177, 195, 229],
         [171, 196, 232],
         [166, 197, 239],
         ...,
         [ 23,  93,  70],
         [ 24,  96,  73],
         [ 30, 102,  79]],

        [[148, 191, 230],
         [146, 188, 230],
         [146, 187, 232],
         ...,
         [ 40,  85,  67],
         [ 29,  85,  70],
         [ 33,  88,  74]],

        ...,

        [[ 19,  31,  35],
         [ 23,  35,  39],
         [ 14,  26,  30],
         ...,
         [ 47, 161, 137],
         [ 54, 172, 147],
         [ 51, 170, 145]],

        [[ 23,  35,  39],
         [ 14,  26,  30],
         [ 12,  24,  28],
         ...,
         [ 43, 157, 134],
         [ 51, 166, 139],
         [ 51, 166, 139]],

        [[ 18,  30,  34],
         [ 11,  23,  27],
         [ 18,  30,  34],
         ...,
         [ 56, 173, 148],
        

In [16]:
all_labels = np.concatenate((
    np.zeros(len(healthy_files)),
    np.ones(len(rust_files)),
))

In [17]:
all_labels

array([0., 0., 0., ..., 1., 1., 1.])

In [18]:
all_files_flat = all_files.reshape(-1, all_files.shape[1] * all_files.shape[2] * all_files.shape[3])

In [20]:
all_files_flat

array([[ 12,  30,  30, ...,  49, 164, 137],
       [  9,  45,  44, ...,  70, 235, 197],
       [ 12,  30,  30, ...,  49, 164, 137],
       ...,
       [251, 253, 247, ...,  87, 122,  95],
       [251, 253, 247, ...,  83, 122,  94],
       [251, 253, 247, ...,  87, 122,  95]], dtype=uint8)

In [21]:
healthy_files_new = all_files_flat[all_labels == 0].reshape(-1, 256, 256, 3)
rust_files_new = all_files_flat[all_labels == 1].reshape(-1, 256, 256, 3)

print("Healthy files shape:", healthy_files_new.shape)
print("Rust files shape:", rust_files_new.shape)

Healthy files shape: (2000, 256, 256, 3)
Rust files shape: (2000, 256, 256, 3)


In [22]:
healthy_files_new

array([[[[ 12,  30,  30],
         [  8,  27,  30],
         [  9,  28,  35],
         ...,
         [ 11,  81,  54],
         [ 10,  77,  50],
         [  8,  75,  49]],

        [[177, 195, 229],
         [171, 196, 232],
         [166, 197, 239],
         ...,
         [ 23,  93,  70],
         [ 24,  96,  73],
         [ 30, 102,  79]],

        [[148, 191, 230],
         [146, 188, 230],
         [146, 187, 232],
         ...,
         [ 40,  85,  67],
         [ 29,  85,  70],
         [ 33,  88,  74]],

        ...,

        [[ 19,  31,  35],
         [ 23,  35,  39],
         [ 14,  26,  30],
         ...,
         [ 47, 161, 137],
         [ 54, 172, 147],
         [ 51, 170, 145]],

        [[ 23,  35,  39],
         [ 14,  26,  30],
         [ 12,  24,  28],
         ...,
         [ 43, 157, 134],
         [ 51, 166, 139],
         [ 51, 166, 139]],

        [[ 18,  30,  34],
         [ 11,  23,  27],
         [ 18,  30,  34],
         ...,
         [ 56, 173, 148],
        

In [23]:
rust_files_new

array([[[[ 30, 109,  66],
         [ 37, 115,  74],
         [ 47, 124,  86],
         ...,
         [ 58,  83, 109],
         [ 78, 105, 126],
         [ 82,  99, 120]],

        [[ 32, 110,  72],
         [ 36, 113,  78],
         [ 42, 118,  87],
         ...,
         [ 65,  96, 112],
         [ 60,  87, 107],
         [ 77,  92, 118]],

        [[ 34, 113,  73],
         [ 37, 115,  77],
         [ 42, 118,  85],
         ...,
         [ 71, 107, 112],
         [ 56,  87, 103],
         [ 73,  90, 117]],

        ...,

        [[ 56, 145,  98],
         [ 68, 151, 106],
         [ 62, 152, 106],
         ...,
         [ 28, 123, 102],
         [ 20, 113,  86],
         [ 26, 109,  77]],

        [[ 52, 146, 101],
         [ 68, 150, 107],
         [ 72, 153, 111],
         ...,
         [ 22, 117,  97],
         [ 17, 111,  83],
         [ 22, 106,  72]],

        [[ 60, 160, 118],
         [ 63, 146, 107],
         [ 55, 130,  92],
         ...,
         [ 28, 122, 105],
        

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [25]:
healthy_files_new = healthy_files_new.astype('float32') / 255.0
rust_files_new = rust_files_new.astype('float32') / 255.0

In [26]:
healthy_files_new

array([[[[0.04705882, 0.11764706, 0.11764706],
         [0.03137255, 0.10588235, 0.11764706],
         [0.03529412, 0.10980392, 0.13725491],
         ...,
         [0.04313726, 0.31764707, 0.21176471],
         [0.03921569, 0.3019608 , 0.19607843],
         [0.03137255, 0.29411766, 0.19215687]],

        [[0.69411767, 0.7647059 , 0.8980392 ],
         [0.67058825, 0.76862746, 0.9098039 ],
         [0.6509804 , 0.77254903, 0.9372549 ],
         ...,
         [0.09019608, 0.3647059 , 0.27450982],
         [0.09411765, 0.3764706 , 0.28627452],
         [0.11764706, 0.4       , 0.30980393]],

        [[0.5803922 , 0.7490196 , 0.9019608 ],
         [0.57254905, 0.7372549 , 0.9019608 ],
         [0.57254905, 0.73333335, 0.9098039 ],
         ...,
         [0.15686275, 0.33333334, 0.2627451 ],
         [0.11372549, 0.33333334, 0.27450982],
         [0.12941177, 0.34509805, 0.2901961 ]],

        ...,

        [[0.07450981, 0.12156863, 0.13725491],
         [0.09019608, 0.13725491, 0.15294118]

In [27]:
rust_files_new

array([[[[0.11764706, 0.42745098, 0.25882354],
         [0.14509805, 0.4509804 , 0.2901961 ],
         [0.18431373, 0.4862745 , 0.3372549 ],
         ...,
         [0.22745098, 0.3254902 , 0.42745098],
         [0.30588236, 0.4117647 , 0.49411765],
         [0.32156864, 0.3882353 , 0.47058824]],

        [[0.1254902 , 0.43137255, 0.28235295],
         [0.14117648, 0.44313726, 0.30588236],
         [0.16470589, 0.4627451 , 0.34117648],
         ...,
         [0.25490198, 0.3764706 , 0.4392157 ],
         [0.23529412, 0.34117648, 0.41960785],
         [0.3019608 , 0.36078432, 0.4627451 ]],

        [[0.13333334, 0.44313726, 0.28627452],
         [0.14509805, 0.4509804 , 0.3019608 ],
         [0.16470589, 0.4627451 , 0.33333334],
         ...,
         [0.2784314 , 0.41960785, 0.4392157 ],
         [0.21960784, 0.34117648, 0.40392157],
         [0.28627452, 0.3529412 , 0.45882353]],

        ...,

        [[0.21960784, 0.5686275 , 0.38431373],
         [0.26666668, 0.5921569 , 0.41568628]

In [28]:
image_shape = (128,128)

In [30]:
X = np.concatenate((healthy_files_new, rust_files_new))
y = np.concatenate(([0]*2000, [1]*2000))

In [31]:
X

array([[[[0.04705882, 0.11764706, 0.11764706],
         [0.03137255, 0.10588235, 0.11764706],
         [0.03529412, 0.10980392, 0.13725491],
         ...,
         [0.04313726, 0.31764707, 0.21176471],
         [0.03921569, 0.3019608 , 0.19607843],
         [0.03137255, 0.29411766, 0.19215687]],

        [[0.69411767, 0.7647059 , 0.8980392 ],
         [0.67058825, 0.76862746, 0.9098039 ],
         [0.6509804 , 0.77254903, 0.9372549 ],
         ...,
         [0.09019608, 0.3647059 , 0.27450982],
         [0.09411765, 0.3764706 , 0.28627452],
         [0.11764706, 0.4       , 0.30980393]],

        [[0.5803922 , 0.7490196 , 0.9019608 ],
         [0.57254905, 0.7372549 , 0.9019608 ],
         [0.57254905, 0.73333335, 0.9098039 ],
         ...,
         [0.15686275, 0.33333334, 0.2627451 ],
         [0.11372549, 0.33333334, 0.27450982],
         [0.12941177, 0.34509805, 0.2901961 ]],

        ...,

        [[0.07450981, 0.12156863, 0.13725491],
         [0.09019608, 0.13725491, 0.15294118]

In [52]:
len(X)

4000

In [32]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [51]:
len(y)

4000

In [33]:
X_resized = np.array([cv2.resize(image, image_shape) for image in X])
X_flattened = X_resized.reshape(X_resized.shape[0], -1)

In [36]:
X_flattened

array([[0.36078432, 0.43921566, 0.5107843 , ..., 0.19607843, 0.64705884,
        0.5411765 ],
       [0.48529413, 0.57058823, 0.5872549 , ..., 0.27745098, 0.9245098 ,
        0.7754902 ],
       [0.36078432, 0.43921566, 0.5107843 , ..., 0.19607843, 0.64705884,
        0.5411765 ],
       ...,
       [0.9843137 , 0.99215686, 0.96862745, ..., 0.3245098 , 0.45294118,
        0.3539216 ],
       [0.9843137 , 0.99215686, 0.96862745, ..., 0.30980393, 0.44215685,
        0.3421569 ],
       [0.9843137 , 0.99215686, 0.96862745, ..., 0.3245098 , 0.45294118,
        0.3539216 ]], dtype=float32)

X_train, X_test, y_train, y_test = train_test_split(X_flattened, y, test_size=0.2, stratify = y, random_state=42)

In [34]:
from sklearn.metrics import f1_score, precision_score, recall_score, classification_report, confusion_matrix

X_train_new = X_train.reshape(-1, 128, 128, 3)
X_test_new = X_test.reshape(-1, 128, 128, 3)

X_train_new

X_test_new

In [35]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models

In [38]:
from tensorflow.keras.models import Sequential

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [41]:
cnn_model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    Flatten(),
    Dense(64, activation='relu'),
])

In [42]:
X_features = cnn_model.predict(X_flattened.reshape(-1, 128, 128, 3))

125/125 [==============================] - 8s 62ms/step


In [43]:
X_train, X_test, y_train, y_test = train_test_split(X_features, y, test_size=0.2, random_state=42)

In [44]:
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

SVC()

In [45]:
y_pred = svm_classifier.predict(X_test)

In [46]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")

Accuracy: 0.78
Precision: 0.80
Recall: 0.72
F1-Score: 0.76
